### ISSUE TITLE
Package is not working properly with NodeJS v12

### ISSUE THREAD

**Issue by willmendesneto** [srijs/node-resumable-hash#2]
When I was trying to upgrade the service which is using this package, I noticed some issues when the install command runs `node-gyp` commands.

As an example, this is the output of the install command when running with NodeJS v12.

<img width="1186" alt="Screen Shot 2020-01-03 at 3 46 40 pm" src="https://user-images.githubusercontent.com/1252570/71707759-4b0ab900-2e40-11ea-8a26-996545bcf9d8.png">

Local configuration:

Python version: 2.7.17
NodeJS version: 12.14.0
OS: MacOS Mojave v10.14.6

---

I got able to solve some warnings/possible issues for NodeJS v10 in this pull request https://github.com/srijs/node-resumable-hash/pull/1 . However, I couldn't fix that easily for NodeJS v12.

**Comment by srijs** [comment]
Fixed and published as `v0.2.5` 🎉 

Please let me know if you come across any other problems.
